### PR TITLE
Add pattern-level blacklisting, add CI, make Clippy happy

### PR DESCRIPTION
**Pull request by quietlychris**

### CODE REVIEW

**Comment by quietlychris** [comment]
Sorry, I'd meant to work on this on my own local branch first! Closing until it's ready to be submitted.

**Comment by j-mendez** [comment]
@quietlychris , recently noticed that some resources are included as links like `.png`.

**Comment by quietlychris** [comment]
@j-mendez Sorry, not sure what you mean? The results that `spider` creates? That was the main thrust of this PR

**Comment by j-mendez** [comment]
Yes exactly, @quietlychris taking a look at this now.

**Comment by quietlychris** [comment]
If you have any questions, just let me know!

**Comment by j-mendez** [comment]
@quietlychris  fixed here https://github.com/madeindjs/spider/pull/30/files. Thanks again!

**Comment by quietlychris** [comment]
Of course! Just to double check: this also rejects files like compressed `.gz` and other binary files?

**Comment by j-mendez** [comment]
> Of course! Just to double check: this also rejects files like compressed `.gz` and other binary files?

Correct, if its not a valid website target for a html resource its ignored =).

**Comment by quietlychris** [comment]
Okay, awesome. Thanks again for this!

**Comment by j-mendez** [comment]
@quietlychris released in v1.5.1.

**Pull request closed without merging**
