### PR TITLE
feat(crawl): callback to run when link is found

### PR DESCRIPTION
**Pull request by j-mendez**
1. add ability to do something on individual link find

Screen Shot 2022-02-10 at 8 53 03 PM

### CODE REVIEW

**Comment by madeindjs** [comment]
Thanks for your contricontribution ❤️ LGTM but can you add a test that callback is called  ?

**Comment by j-mendez** [comment]
> Thanks for your contricontribution ❤️ LGTM but can you add a test that callback is called ?

Your welcome! Yes I will get to this by the EOD. 🙌

**Comment by j-mendez** [comment]
@madeindjs added a quick test, should be good to go =)

**Review by madeindjs — APPROVED** [review]

**Comment by madeindjs** [comment]
Thank for your contribution :heart:

**Comment by madeindjs** [comment]
published on [v1.3.0](https://github.com/madeindjs/spider/releases/tag/v1.3.0)

**Pull request merged**
